"""Deterministic immutable-release construction and attestation."""

from .manifest import (
    BuildResult,
    ReleasePolicy,
    build_release,
    create_manifest,
    phase4_app_release_policy,
    phase4_backend_release_policy,
    verify_release,
    write_manifest,
)
from .backend_policy import (
    APPROVED_PHASE4_BACKEND_COMMIT, PHASE4_BACKEND_AUDITED_PATHS,
    phase4_backend_policy, require_approved_backend_commit,
    verify_phase4_backend_release,
)
from .config import (
    AUTHORITY_PATH,
    ProtectedAuthorityError,
    RELEASE_ACTIVATION_V2_PATH,
    RUNTIME_AUTHORITY_V2_PATH,
    RuntimeAuthority,
    RuntimeAuthorityV2,
    RuntimePathsV2,
    attest_application_release,
    attest_application_release_v2,
    attest_application_authority,
    load_runtime_authority,
    load_runtime_authority_v2,
    read_protected_canonical_json,
    read_protected_canonical_json_current,
    read_protected_file_current,
)
from .semantic import (
    SemanticAttestationError,
    attest_current_semantic_inputs,
    semantic_policy_digest,
    semantic_policy_digest_v2,
)
from .job_plane import ValidatedJobPlaneAuthority, validate_job_plane_authority
from .offline_wheelhouse import (
    MANIFEST_NAME as WHEELHOUSE_MANIFEST_NAME,
    build_wheelhouse_manifest,
    verify_offline_wheelhouse,
    write_wheelhouse_manifest,
)

__all__ = [
    "BuildResult",
    "ReleasePolicy",
    "build_release",
    "create_manifest",
    "phase4_app_release_policy",
    "phase4_backend_release_policy",
    "PHASE4_BACKEND_AUDITED_PATHS",
    "APPROVED_PHASE4_BACKEND_COMMIT",
    "phase4_backend_policy",
    "require_approved_backend_commit",
    "verify_phase4_backend_release",
    "verify_release",
    "write_manifest",
    "AUTHORITY_PATH",
    "ProtectedAuthorityError",
    "RuntimeAuthority",
    "RuntimeAuthorityV2",
    "RuntimePathsV2",
    "attest_application_release",
    "attest_application_authority",
    "load_runtime_authority",
    "load_runtime_authority_v2",
    "RUNTIME_AUTHORITY_V2_PATH",
    "RELEASE_ACTIVATION_V2_PATH",
    "attest_application_release_v2",
    "read_protected_canonical_json",
    "read_protected_canonical_json_current",
    "read_protected_file_current",
    "SemanticAttestationError",
    "attest_current_semantic_inputs",
    "semantic_policy_digest",
    "semantic_policy_digest_v2",
    "ValidatedJobPlaneAuthority",
    "validate_job_plane_authority",
    "WHEELHOUSE_MANIFEST_NAME",
    "build_wheelhouse_manifest",
    "verify_offline_wheelhouse",
    "write_wheelhouse_manifest",
]
