"""
Database schema for trading agent.
SQLite with WAL mode for concurrent reads during writes.
"""

import sqlite3
import logging
from pathlib import Path

log = logging.getLogger(__name__)

# ── Schema ─────────────────────────────────────────────────────

SCHEMA = """
-- Orders: all order attempts (pending → open → filled/canceled/rejected)
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    client_order_id TEXT UNIQUE NOT NULL,
    exchange_order_id TEXT,
    idempotency_key TEXT,
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL CHECK(side IN ('buy', 'sell')),
    order_type TEXT NOT NULL CHECK(order_type IN ('market', 'limit', 'stop_loss', 'stop_loss_limit', 'take_profit', 'take_profit_limit')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'open', 'partially_filled', 'filled', 'canceled', 'expired', 'rejected')),
    quantity REAL NOT NULL,
    price REAL,
    stop_price REAL,
    filled_quantity REAL DEFAULT 0,
    avg_fill_price REAL,
    commission REAL,
    commission_asset TEXT,
    raw_json TEXT,
    signal_id INTEGER REFERENCES signals(id),
    strategy TEXT,
    error_message TEXT,
    reduce_only INTEGER DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_orders_symbol ON orders(symbol);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_client_id ON orders(client_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_idempotency ON orders(idempotency_key);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);

-- Positions: current holdings with risk parameters
CREATE TABLE IF NOT EXISTS positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    quantity REAL NOT NULL DEFAULT 0,
    avg_entry_price REAL,
    current_price REAL,
    unrealized_pnl REAL DEFAULT 0,
    realized_pnl REAL DEFAULT 0,
    stop_loss REAL,                  -- Absolute stop-loss price
    take_profit REAL,                -- Absolute take-profit price
    trailing_stop INTEGER DEFAULT 0, -- 1 = trailing stop active
    trailing_distance_pct REAL,      -- Trail distance as decimal (0.05 = 5%)
    highest_price REAL,              -- Highest price seen (for trailing stop calc)
    stop_triggered_at TEXT,          -- ISO timestamp when last stop triggered
    opened_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(exchange, symbol)
);

CREATE INDEX IF NOT EXISTS idx_positions_symbol ON positions(symbol);

-- Trades: individual fills (one order can have multiple fills)
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    exchange_order_id TEXT,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    quantity REAL NOT NULL,
    price REAL NOT NULL,
    commission REAL,
    commission_asset TEXT,
    trade_timestamp TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_trades_order ON trades(order_id);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_timestamp ON trades(trade_timestamp);

-- Signals: generated by research pipeline
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL CHECK(direction IN ('BUY', 'SELL', 'HOLD')),
    confidence REAL,
    strategy TEXT,
    source TEXT,
    metadata_json TEXT,
    processed INTEGER DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_created ON signals(created_at);

-- Equity snapshots: periodic portfolio value
CREATE TABLE IF NOT EXISTS equity_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    total_equity REAL NOT NULL,
    cash REAL NOT NULL,
    positions_value REAL NOT NULL,
    unrealized_pnl REAL NOT NULL,
    realized_pnl REAL NOT NULL,
    daily_pnl REAL,
    drawdown_pct REAL
);

CREATE INDEX IF NOT EXISTS idx_equity_timestamp ON equity_snapshots(timestamp);

-- Alerts: system notifications
CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL CHECK(type IN ('info', 'warning', 'error', 'trade', 'system')),
    severity TEXT NOT NULL DEFAULT 'info' CHECK(severity IN ('info', 'warning', 'critical')),
    message TEXT NOT NULL,
    metadata_json TEXT,
    acknowledged INTEGER DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_ack ON alerts(acknowledged);

-- Agent state: persistent runtime state
CREATE TABLE IF NOT EXISTS agent_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Alpha Arena: LLM agents compete on the same market data
CREATE TABLE IF NOT EXISTS arena_competitions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    started_at TEXT NOT NULL DEFAULT (datetime('now')),
    ended_at TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','completed','cancelled')),
    config_json TEXT
);
CREATE TABLE IF NOT EXISTS arena_rounds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    competition_id INTEGER NOT NULL REFERENCES arena_competitions(id),
    symbol TEXT NOT NULL,
    round_number INTEGER NOT NULL,
    price REAL NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(competition_id, symbol, round_number)
);
CREATE TABLE IF NOT EXISTS arena_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    round_id INTEGER NOT NULL REFERENCES arena_rounds(id),
    analyst TEXT NOT NULL,
    action TEXT NOT NULL CHECK(action IN ('BUY','SELL','HOLD','WATCH')),
    confidence REAL NOT NULL,
    entry_price REAL,
    stop_loss REAL,
    take_profit REAL,
    reasoning TEXT,
    pnl_impact REAL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS arena_portfolios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    competition_id INTEGER NOT NULL REFERENCES arena_competitions(id),
    analyst TEXT NOT NULL,
    cash REAL NOT NULL DEFAULT 100000,
    equity REAL NOT NULL DEFAULT 100000,
    pnl REAL NOT NULL DEFAULT 0,
    trades INTEGER NOT NULL DEFAULT 0,
    win_rate REAL DEFAULT 0,
    sharpe REAL DEFAULT 0,
    max_drawdown REAL DEFAULT 0,
    UNIQUE(competition_id, analyst)
);
"""

# Queries used by repository layer
QUERIES = {
    "upsert_position": """
        INSERT INTO positions (exchange, symbol, quantity, avg_entry_price, current_price,
                               unrealized_pnl, realized_pnl,
                               stop_loss, take_profit, trailing_stop, trailing_distance_pct,
                               highest_price, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
        ON CONFLICT(exchange, symbol) DO UPDATE SET
            quantity = excluded.quantity,
            avg_entry_price = excluded.avg_entry_price,
            current_price = excluded.current_price,
            unrealized_pnl = excluded.unrealized_pnl,
            realized_pnl = excluded.realized_pnl,
            stop_loss = excluded.stop_loss,
            take_profit = excluded.take_profit,
            trailing_stop = excluded.trailing_stop,
            trailing_distance_pct = excluded.trailing_distance_pct,
            highest_price = excluded.highest_price,
            updated_at = excluded.updated_at
    """,
    "get_open_orders": """
        SELECT * FROM orders WHERE status IN ('pending', 'open', 'partially_filled')
        ORDER BY created_at DESC
    """,
    "get_recent_fills": """
        SELECT o.symbol, o.side, t.quantity, t.price, t.commission, t.trade_timestamp
        FROM trades t
        JOIN orders o ON t.order_id = o.id
        ORDER BY t.trade_timestamp DESC
        LIMIT ?
    """,
    "get_pnl_summary": """
        SELECT
            SUM(realized_pnl) as total_realized_pnl,
            SUM(unrealized_pnl) as total_unrealized_pnl,
            COUNT(*) as position_count
        FROM positions
        WHERE quantity != 0
    """,
}

# ── Migration ──────────────────────────────────────────────────

# Columns added in v2: stop_loss, take_profit, trailing_stop, etc.
MIGRATIONS = [
    "ALTER TABLE positions ADD COLUMN stop_loss REAL",
    "ALTER TABLE positions ADD COLUMN take_profit REAL",
    "ALTER TABLE positions ADD COLUMN trailing_stop INTEGER DEFAULT 0",
    "ALTER TABLE positions ADD COLUMN trailing_distance_pct REAL",
    "ALTER TABLE positions ADD COLUMN highest_price REAL",
    "ALTER TABLE positions ADD COLUMN stop_triggered_at TEXT",
]


def run_migrations(db_path: str):
    """Apply schema migrations incrementally. Idempotent — safe to run every startup."""
    conn = sqlite3.connect(db_path)
    try:
        existing = {row[1] for row in conn.execute("PRAGMA table_info(positions)").fetchall()}

        for migration in MIGRATIONS:
            # Extract column name from "ALTER TABLE ... ADD COLUMN <name> <type>"
            parts = migration.split()
            col_idx = parts.index("COLUMN") + 1 if "COLUMN" in parts else 3
            col_name = parts[col_idx]
            if col_name in existing:
                continue
            try:
                conn.execute(migration)
                conn.commit()
                log.info("Migration applied: ADD COLUMN %s", col_name)
            except sqlite3.OperationalError as e:
                log.warning("Migration skipped (%s): %s", col_name, e)

        # Verify all columns exist
        final = {row[1] for row in conn.execute("PRAGMA table_info(positions)").fetchall()}
        log.info("Positions table columns: %s", sorted(final))
    finally:
        conn.close()
