#!/usr/bin/env python3
"""
sentiment_collector.py — News sentiment pipeline using VADER.

Reads news articles from the latest news_report_*.json (generated by news_collector.py),
applies VADER sentiment scoring, and writes a structured sentiment report.

Output: reports/sentiment_report_<timestamp>.json

Scoring:
- VADER compound score normalized to [-1, +1] per article
- Per-asset aggregation with thresholds:
  > 0.3 = bullish bonus, < -0.3 = bearish penalty
- Wired into assembly.py signal scoring at 0.15 weight.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from runtime_paths import reports_dir
from typing import Optional

log = logging.getLogger("sentiment_collector")

OUTPUT_DIR = reports_dir()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

NOW = datetime.now(timezone.utc).isoformat()

# Assets to track sentiment for
WATCHLIST = [
    "BTC", "ETH", "SOL", "TON", "DOGE", "ADA", "AVAX", "DOT", "LINK", "MATIC",
    "AAPL", "NVDA", "MSFT", "GOOGL", "AMZN", "META", "TSLA",
    "SPY", "QQQ",
]


def _get_vader():
    """Lazy-load VADER SentimentIntensityAnalyzer."""
    try:
        from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
        return SentimentIntensityAnalyzer()
    except ImportError:
        log.warning("vaderSentiment not installed — returning None")
        return None


def _score_text(text: str, analyzer) -> float:
    """Score a single text with VADER, return compound score [-1, 1]."""
    if analyzer is None:
        return 0.0
    try:
        scores = analyzer.polarity_scores(text)
        return scores.get("compound", 0.0)
    except Exception:
        return 0.0


def _load_latest_news() -> Optional[dict]:
    """Load the latest news report from reports/. """
    news_files = sorted(OUTPUT_DIR.glob("news_report_*.json"))
    if not news_files:
        log.warning("No news_report_*.json files found")
        return None
    try:
        return json.loads(news_files[-1].read_text())
    except Exception as e:
        log.warning("Failed to load news report: %s", e)
        return None


def compute_sentiment(articles: list[dict], analyzer) -> dict[str, dict]:
    """
    Compute per-asset sentiment from article headlines.
    Returns dict keyed by symbol with scores and distributions.
    """
    by_asset: dict[str, list[tuple[str, float]]] = {}

    for art in articles:
        headline = art.get("title", "")
        if not headline:
            continue
        score = _score_text(headline, analyzer)
        sym = art.get("symbol", "UNKNOWN").upper()
        if sym not in by_asset:
            by_asset[sym] = []
        by_asset[sym].append((headline, score))

    result = {}
    for sym, scored in sorted(by_asset.items()):
        if not scored:
            continue
        scores = [s for _, s in scored]
        avg_score = sum(scores) / len(scores)

        positive = sum(1 for s in scores if s > 0.3)
        negative = sum(1 for s in scores if s < -0.3)
        neutral = len(scores) - positive - negative

        # Determine overall sentiment
        if avg_score > 0.3:
            sentiment = "positive"
        elif avg_score < -0.3:
            sentiment = "negative"
        else:
            sentiment = "neutral"

        # Articles with high absolute scores (top 5)
        top_articles = sorted(scored, key=lambda x: abs(x[1]), reverse=True)[:5]

        result[sym] = {
            "sentiment": sentiment,
            "avg_score": round(avg_score, 4),
            "positive_count": positive,
            "negative_count": negative,
            "neutral_count": neutral,
            "articles_found": len(scores),
            "top_articles": [
                {"title": h[:120], "score": round(s, 4)} for h, s in top_articles
            ],
        }

    return result


def collect_sentiment() -> dict:
    """Main sentiment collection pipeline."""
    analyzer = _get_vader()
    news_report = _load_latest_news()

    if not news_report:
        return {
            "timestamp": NOW,
            "source": "vader",
            "assets": {},
            "error": "No news report available",
        }

    articles = news_report.get("articles", [])
    if not articles:
        return {
            "timestamp": NOW,
            "source": "vader",
            "assets": {},
            "error": "No articles in news report",
        }

    assets = compute_sentiment(articles, analyzer)
    overall_sentiment = "neutral"
    if assets:
        all_scores = [a["avg_score"] for a in assets.values()]
        if all_scores:
            overall_avg = sum(all_scores) / len(all_scores)
            if overall_avg > 0.15:
                overall_sentiment = "bullish"
            elif overall_avg < -0.15:
                overall_sentiment = "bearish"

    return {
        "timestamp": NOW,
        "source": "vader",
        "overall_sentiment": overall_sentiment,
        "assets_scored": len(assets),
        "assets": assets,
    }


def get_sentiment_for_asset(symbol: str) -> dict:
    """
    Get sentiment data for a specific asset from the latest sentiment report.
    Used by assembly.py signal scoring.
    Returns dict with sentiment, score, and details.
    """
    sentiment_files = sorted(OUTPUT_DIR.glob("sentiment_report_*.json"))
    if not sentiment_files:
        return {"sentiment": None, "sentiment_score": None}

    try:
        report = json.loads(sentiment_files[-1].read_text())
    except Exception:
        return {"sentiment": None, "sentiment_score": None}

    asset_data = report.get("assets", {}).get(symbol.upper(), {})
    if not asset_data:
        return {"sentiment": None, "sentiment_score": None}

    return {
        "sentiment": asset_data.get("sentiment"),
        "sentiment_score": asset_data.get("avg_score"),
        "sentiment_source": f"vader/{report.get('source', 'unknown')}",
        "sentiment_distribution": {
            "positive": asset_data.get("positive_count", 0),
            "negative": asset_data.get("negative_count", 0),
            "neutral": asset_data.get("neutral_count", 0),
        },
        "sentiment_summary": f"Sentiment: {asset_data.get('sentiment', 'neutral')} ({asset_data.get('avg_score', 0):+.2f})",
        "articles_found": asset_data.get("articles_found", 0),
        "articles_scored": asset_data.get("articles_found", 0),
        "articles_filtered": 0,
    }


def main():
    report = collect_sentiment()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = OUTPUT_DIR / f"sentiment_report_{ts}.json"

    # Keep last 10 sentiment reports
    old_reports = sorted(OUTPUT_DIR.glob("sentiment_report_*.json"))
    for old in old_reports[:-9]:
        old.unlink(missing_ok=True)

    with open(out_path, "w") as f:
        json.dump(report, f, indent=2)

    print(f"Sentiment report written to {out_path}")
    print(f"  Overall: {report.get('overall_sentiment', 'neutral')}")
    print(f"  Assets scored: {report.get('assets_scored', 0)}")
    for sym, data in sorted(report.get("assets", {}).items()):
        print(f"    {sym}: {data.get('sentiment', '?')} ({data.get('avg_score', 0):+.3f}) [{data.get('articles_found', 0)} articles]")


if __name__ == "__main__":
    main()
