#!/usr/bin/env python3
"""Generate the stdlib-only P1 Nautilus wire grammar."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from packages.engine_contracts import canonical_json_bytes
from packages.nautilus_runtime_contracts import (
    P1EngineConfigurationV1,
    P1InstrumentCatalogV1,
    P1MarketDataManifestV1,
    P1TargetScheduleV1,
)
from packages.nautilus_runtime_contracts.events import P1_EVENT_ADAPTER, P1_EVENT_MODELS


ARTIFACT_MODELS = {
    "engine_configuration": P1EngineConfigurationV1,
    "instrument_catalog": P1InstrumentCatalogV1,
    "market_data_manifest": P1MarketDataManifestV1,
    "target_schedule": P1TargetScheduleV1,
}
CONTRACT_FIXTURES = {
    "engine_configuration": "engine-configuration.json",
    "instrument_catalog": "instrument-catalog.json",
    "market_data_manifest": "market-data-manifest.json",
    "target_schedule": "target-schedule.json",
}


def _json(value: object) -> bytes:
    return (
        json.dumps(value, allow_nan=False, ensure_ascii=False, indent=2, sort_keys=True)
        + "\n"
    ).encode()


def _grammar() -> tuple[dict[str, tuple[str, ...]], dict[str, dict[str, object]]]:
    fields = {name: tuple(model.model_fields) for name, model in ARTIFACT_MODELS.items()}
    fields.update(
        {
            model.model_json_schema(mode="validation")["properties"]["event_type"]["const"]: tuple(model.model_fields)
            for model in P1_EVENT_MODELS
        }
    )
    constants: dict[str, dict[str, object]] = {}
    for name, model in (
        tuple(ARTIFACT_MODELS.items())
        + tuple(
            (
                model.model_json_schema(mode="validation")["properties"]["event_type"]["const"],
                model,
            )
            for model in P1_EVENT_MODELS
        )
    ):
        properties = model.model_json_schema(mode="validation")["properties"]
        constants[name] = {
            field_name: field_schema["const"]
            for field_name, field_schema in properties.items()
            if "const" in field_schema
        }
    return fields, constants


def _schemas() -> dict[str, dict[str, object]]:
    schemas = {
        name: model.model_json_schema(mode="validation")
        for name, model in ARTIFACT_MODELS.items()
    }
    schemas.update(
        {
            model.model_json_schema(mode="validation")["properties"]["event_type"]["const"]: model.model_json_schema(mode="validation")
            for model in P1_EVENT_MODELS
        }
    )
    return schemas


def _module_bytes() -> bytes:
    fields, constants = _grammar()
    schemas = _schemas()
    source = f'''# GENERATED by scripts/generate_nautilus_p1_protocol.py. DO NOT EDIT.
from __future__ import annotations

import json
import re
import uuid

P1_EVENT_SCHEMA = "nautilus-p1-event-stream-v1"
DECIMAL_PATTERN = r"^(?:0|-?[1-9]\\d*|-?(?:0|[1-9]\\d*)\\.\\d*[1-9])$"
TIMESTAMP_PATTERN = r"^\\d{{4}}-\\d{{2}}-\\d{{2}}T\\d{{2}}:\\d{{2}}:\\d{{2}}(?:\\.\\d{{1,6}})?Z$"
IDENTIFIER_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9._:-]{{0,127}}$"
SHA256_PATTERN = r"^[0-9a-f]{{64}}$"
DOCUMENT_FIELDS = {fields!r}
CONSTANT_FIELDS = {constants!r}
DOCUMENT_SCHEMAS = {schemas!r}


class ProtocolValidationError(ValueError):
    code = "E_PROTOCOL"


def _reject_float(_: str) -> object:
    raise ProtocolValidationError("floating JSON number")


def canonical_json_bytes(value: object) -> bytes:
    def walk(item: object) -> None:
        if isinstance(item, float):
            raise ProtocolValidationError("floating value")
        if isinstance(item, dict):
            if not all(isinstance(key, str) for key in item):
                raise ProtocolValidationError("non-string key")
            for child in item.values():
                walk(child)
        elif isinstance(item, (list, tuple)):
            for child in item:
                walk(child)
        elif item is not None and not isinstance(item, (str, bool, int)):
            raise ProtocolValidationError("unsupported value")
    walk(value)
    return json.dumps(value, allow_nan=False, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode()


def load_canonical_json(raw: bytes) -> dict[str, object]:
    def pairs(items: list[tuple[str, object]]) -> dict[str, object]:
        value: dict[str, object] = {{}}
        for key, item in items:
            if key in value:
                raise ProtocolValidationError("duplicate key")
            value[key] = item
        return value
    if not raw.endswith(b"\\n") or raw.endswith(b"\\n\\n"):
        raise ProtocolValidationError("trailing newline")
    try:
        value = json.loads(raw[:-1], object_pairs_hook=pairs, parse_float=_reject_float, parse_constant=_reject_float)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ProtocolValidationError("invalid JSON") from exc
    if not isinstance(value, dict) or canonical_json_bytes(value) + b"\\n" != raw:
        raise ProtocolValidationError("noncanonical JSON")
    return value


def _validate(value: object, schema: dict[str, object], root: dict[str, object]) -> None:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        if not reference.startswith("#/$defs/"):
            raise ProtocolValidationError("external schema reference")
        target = root.get("$defs", {{}}).get(reference.removeprefix("#/$defs/"))
        if not isinstance(target, dict):
            raise ProtocolValidationError("missing schema reference")
        _validate(value, target, root)
        return
    alternatives = schema.get("anyOf") or schema.get("oneOf")
    if isinstance(alternatives, list):
        matches = 0
        for alternative in alternatives:
            try:
                _validate(value, alternative, root)
            except ProtocolValidationError:
                continue
            matches += 1
        if matches != 1:
            raise ProtocolValidationError("schema union")
        return
    if "const" in schema and (value != schema["const"] or type(value) is not type(schema["const"])):
        raise ProtocolValidationError("constant field")
    enum = schema.get("enum")
    if isinstance(enum, list) and value not in enum:
        raise ProtocolValidationError("enum field")
    expected_type = schema.get("type")
    type_checks = {{
        "object": lambda item: type(item) is dict,
        "array": lambda item: type(item) is list,
        "string": lambda item: type(item) is str,
        "integer": lambda item: type(item) is int,
        "boolean": lambda item: type(item) is bool,
        "null": lambda item: item is None,
    }}
    if isinstance(expected_type, str) and expected_type in type_checks and not type_checks[expected_type](value):
        raise ProtocolValidationError("field type")
    if type(value) is dict:
        properties = schema.get("properties", {{}})
        required = schema.get("required", [])
        if not isinstance(properties, dict) or not isinstance(required, list):
            raise ProtocolValidationError("object schema")
        if not set(required) <= set(value):
            raise ProtocolValidationError("missing field")
        if schema.get("additionalProperties") is False and set(value) - set(properties):
            raise ProtocolValidationError("unknown field")
        for name, item in value.items():
            child = properties.get(name)
            if isinstance(child, dict):
                _validate(item, child, root)
    elif type(value) is list:
        if len(value) < schema.get("minItems", 0) or len(value) > schema.get("maxItems", len(value)):
            raise ProtocolValidationError("array length")
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for item in value:
                _validate(item, item_schema, root)
    elif type(value) is str:
        if len(value) < schema.get("minLength", 0) or len(value) > schema.get("maxLength", len(value)):
            raise ProtocolValidationError("string length")
        pattern = schema.get("pattern")
        if isinstance(pattern, str) and re.fullmatch(pattern, value) is None:
            raise ProtocolValidationError("string pattern")
        if schema.get("format") == "uuid":
            try:
                if str(uuid.UUID(value)) != value:
                    raise ValueError
            except ValueError as exc:
                raise ProtocolValidationError("UUID") from exc
    elif type(value) is int:
        if "minimum" in schema and value < schema["minimum"]:
            raise ProtocolValidationError("integer minimum")
        if "maximum" in schema and value > schema["maximum"]:
            raise ProtocolValidationError("integer maximum")
        if "exclusiveMinimum" in schema and value <= schema["exclusiveMinimum"]:
            raise ProtocolValidationError("integer exclusive minimum")


def validate_document(kind: str, value: dict[str, object]) -> None:
    schema = DOCUMENT_SCHEMAS.get(kind)
    if schema is None:
        raise ProtocolValidationError("document kind")
    canonical_json_bytes(value)
    _validate(value, schema, schema)
'''
    return source.encode()


def _outputs() -> dict[Path, bytes]:
    outputs = {Path("engines/nautilus/runtime_v1/generated_protocol.py"): _module_bytes()}
    for name, model in ARTIFACT_MODELS.items():
        outputs[Path(f"schemas/nautilus-p1-{name.replace('_', '-')}-v1.schema.json")] = _json(
            model.model_json_schema(mode="validation")
        )
    outputs[Path("schemas/nautilus-p1-event-stream-v1.schema.json")] = _json(
        P1_EVENT_ADAPTER.json_schema(mode="validation")
    )
    fixture_root = ROOT / "tests/fixtures/p1_nautilus/contracts"
    for kind, filename in CONTRACT_FIXTURES.items():
        raw = (fixture_root / filename).read_bytes()
        outputs[Path(f"tests/fixtures/p1_nautilus/golden/positive/{kind}.json")] = raw
        value = json.loads(raw)
        value["unknown"] = True
        outputs[Path(f"tests/fixtures/p1_nautilus/golden/negative/{kind}.json")] = canonical_json_bytes(value) + b"\n"
    return outputs


def generate(output_root: Path, *, check: bool) -> int:
    stale: list[str] = []
    for relative, raw in _outputs().items():
        path = output_root / relative
        if check:
            if not path.is_file() or path.read_bytes() != raw:
                stale.append(relative.as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(raw)
    if stale:
        print("stale P1 Nautilus generated files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-root", type=Path, default=ROOT)
    args = parser.parse_args()
    return generate(args.output_root.resolve(), check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
