"""Public immutable D0.1 primitives and D0.2 canonical contracts."""

from __future__ import annotations

from .clock import FixedUtcClock, SystemUtcClock, require_utc
from .instruments import (
    AssetClass,
    InstrumentConstraints,
    InstrumentDefinition,
    InstrumentId,
    InstrumentProvenance,
    MarginRequirements,
    ProductType,
)
from .market_data import (
    MarketCandle,
    MarketContinuity,
    MarketDataProvenance,
    MarketSnapshot,
    MarketTimeframe,
    normalize_market_symbol,
)
from .events import EventEnvelope, validate_event_batch
from .orders import (
    ORDER_STATUS_TRANSITIONS,
    TERMINAL_ORDER_STATUSES,
    FillEvent,
    OrderCancelResolution,
    OrderEvent,
    OrderIntent,
    OrderReductionError,
    OrderSide,
    OrderState,
    OrderStatus,
    OrderType,
    TimeInForce,
    reduce_order,
)
from .portfolio import PortfolioSnapshot, PositionSnapshot, TargetPortfolio, TargetPosition
from .primitives import (
    CANONICAL_DECIMAL_POLICY_VERSION,
    DEFAULT_CURRENCY_REGISTRY,
    Currency,
    CurrencyConversion,
    CurrencyRegistry,
    CurrencyType,
    FiniteDecimal,
    Money,
    OrderQuantity,
    Price,
    Quantity,
    convert_money_exact,
    decimal_to_scaled_integer,
)
from .risk import RiskDecision, RiskOutcome, RiskReasonCode, RiskStateSnapshot
from .signals import (
    EvidenceLocator,
    EvidenceLocatorKind,
    EvidenceReference,
    EvidenceSource,
    ResearchPacket,
    SignalDirection,
    SignalProposal,
)

__all__ = [
    "CANONICAL_DECIMAL_POLICY_VERSION",
    "AssetClass",
    "Currency",
    "CurrencyConversion",
    "CurrencyRegistry",
    "CurrencyType",
    "DEFAULT_CURRENCY_REGISTRY",
    "EventEnvelope",
    "EvidenceLocator",
    "EvidenceLocatorKind",
    "EvidenceReference",
    "EvidenceSource",
    "FillEvent",
    "FiniteDecimal",
    "FixedUtcClock",
    "InstrumentConstraints",
    "InstrumentDefinition",
    "InstrumentId",
    "InstrumentProvenance",
    "MarginRequirements",
    "Money",
    "MarketCandle",
    "MarketContinuity",
    "MarketDataProvenance",
    "MarketSnapshot",
    "MarketTimeframe",
    "ORDER_STATUS_TRANSITIONS",
    "OrderCancelResolution",
    "OrderEvent",
    "OrderIntent",
    "OrderQuantity",
    "OrderReductionError",
    "OrderSide",
    "OrderState",
    "OrderStatus",
    "OrderType",
    "PortfolioSnapshot",
    "PositionSnapshot",
    "Price",
    "ProductType",
    "Quantity",
    "ResearchPacket",
    "RiskDecision",
    "RiskOutcome",
    "RiskReasonCode",
    "RiskStateSnapshot",
    "SignalDirection",
    "SignalProposal",
    "SystemUtcClock",
    "TargetPortfolio",
    "TargetPosition",
    "TERMINAL_ORDER_STATUSES",
    "TimeInForce",
    "convert_money_exact",
    "decimal_to_scaled_integer",
    "require_utc",
    "validate_event_batch",
    "normalize_market_symbol",
    "reduce_order",
]
