"""Dependency-free extraction of redacted restore-proof failure codes."""

from __future__ import annotations

from collections.abc import Iterable
import re


RESTORE_PROOF_INVALID_FAILURE_CODE = "RESTORE_PROOF_INVALID_FAILURE_CODE"
NO_RESTORE_PROOF_CODE = "RESTORE_PROOF_NO_CODE"

RESTORE_PROOF_FAILURE_CODES = frozenset(
    {
        "RESTORE_PROOF_SOURCE_EXACT_HEAD_MISMATCH",
        "RESTORE_PROOF_TARGET_BASE_EXACT_HEAD_MISMATCH",
        "RESTORE_PROOF_TARGET_RESTORED_EXACT_HEAD_MISMATCH",
        "RESTORE_PROOF_SOURCE_ROLE_SETTINGS_MISMATCH",
        "RESTORE_PROOF_TARGET_ROLE_SETTINGS_MISMATCH",
        "RESTORE_PROOF_TARGET_POST_DROP_ROLE_SETTINGS_MISMATCH",
        "RESTORE_PROOF_TARGET_POST_RESTORE_ROLE_SETTINGS_MISMATCH",
        "RESTORE_PROOF_TARGET_PROVISIONED_GLOBAL_ROLE_EVIDENCE_MISMATCH",
        "RESTORE_PROOF_TARGET_POST_DROP_GLOBAL_ROLE_EVIDENCE_MISMATCH",
        "RESTORE_PROOF_TARGET_POST_RESTORE_GLOBAL_ROLE_EVIDENCE_MISMATCH",
        "RESTORE_PROOF_EFFECTIVE_DATABASE_ACL_MISMATCH",
        "RESTORE_PROOF_EFFECTIVE_DATABASE_ACL_MALFORMED_EVIDENCE",
        "RESTORE_PROOF_EFFECTIVE_DATABASE_ACL_NON_CANONICAL_EVIDENCE",
        "RESTORE_PROOF_EFFECTIVE_DATABASE_ACL_SELECTED_OBJECTS_MISMATCH",
        "RESTORE_PROOF_RESTORED_ROW_COUNTS_MISMATCH",
        "RESTORE_PROOF_POST_DENIAL_ROW_COUNTS_MISMATCH",
        "RESTORE_PROOF_ROW_COUNT_EVIDENCE_MISSING",
        "RESTORE_PROOF_RESTORED_CATALOG_DIGEST_MISMATCH",
        "RESTORE_PROOF_RESTORED_EVENT_CHAIN_MISMATCH",
        "RESTORE_PROOF_POST_DENIAL_CATALOG_DIGEST_MISMATCH",
        "RESTORE_PROOF_POST_DENIAL_EVENT_CHAIN_MISMATCH",
        "RESTORE_PROOF_RESTORED_CATALOG_DATABASE_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_SCHEMA_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_OBJECT_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_OBJECT_ACL_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_OBJECT_OWNER_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_OBJECT_METADATA_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_OBJECT_IDENTITY_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_COLUMN_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_CONSTRAINT_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_INDEX_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_SEQUENCE_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_FUNCTION_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_TRIGGER_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_POLICY_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_DEFAULT_ACL_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_ROLE_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_MEMBERSHIP_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_ROLE_SETTING_DRIFT",
        "RESTORE_PROOF_RESTORED_CATALOG_MALFORMED_OR_UNKNOWN",
        "RESTORE_PROOF_CLUSTER_ROOT_ISOLATION_MISMATCH",
        "RESTORE_PROOF_CLUSTER_DATA_ISOLATION_MISMATCH",
        "RESTORE_PROOF_CLUSTER_PORT_ISOLATION_MISMATCH",
        "RESTORE_PROOF_TARGET_DROP_MAINTENANCE_CONTEXT_MISMATCH",
        "RESTORE_PROOF_TARGET_DATABASE_DROP_MISMATCH",
        "RESTORE_PROOF_SOURCE_PREPARATION_DUMP_FAILURE",
        "RESTORE_PROOF_TARGET_BOOTSTRAP_DROP_FAILURE",
        "RESTORE_PROOF_RESTORE_EXECUTION_FAILURE",
        "RESTORE_PROOF_POST_RESTORE_VERIFICATION_FAILURE",
    }
)
RESTORE_PROOF_REPORTABLE_FAILURE_CODES = RESTORE_PROOF_FAILURE_CODES | frozenset(
    {RESTORE_PROOF_INVALID_FAILURE_CODE}
)

_PYTEST_FAILURE_LINE = re.compile(
    r"^E\s+AssertionError:\s+(RESTORE_PROOF_[A-Z0-9_]+)$"
)


def _line_without_ending(line: str) -> str:
    if line.endswith("\n"):
        line = line[:-1]
    if line.endswith("\r"):
        line = line[:-1]
    return line


def extract_restore_proof_failure_code(lines: Iterable[str]) -> str:
    """Return one allowlisted code, or the fixed no-code sentinel.

    Input is consumed one line at a time. No private input is returned or used in
    diagnostics.
    """

    selected_code: str | None = None
    try:
        for line in lines:
            if not isinstance(line, str):
                return NO_RESTORE_PROOF_CODE
            match = _PYTEST_FAILURE_LINE.fullmatch(_line_without_ending(line))
            if match is None:
                continue
            candidate_code = match.group(1)
            if candidate_code not in RESTORE_PROOF_REPORTABLE_FAILURE_CODES:
                return NO_RESTORE_PROOF_CODE
            if selected_code is not None:
                return NO_RESTORE_PROOF_CODE
            selected_code = candidate_code
    except Exception:
        return NO_RESTORE_PROOF_CODE
    return selected_code if selected_code is not None else NO_RESTORE_PROOF_CODE


__all__ = (
    "NO_RESTORE_PROOF_CODE",
    "RESTORE_PROOF_FAILURE_CODES",
    "RESTORE_PROOF_INVALID_FAILURE_CODE",
    "RESTORE_PROOF_REPORTABLE_FAILURE_CODES",
    "extract_restore_proof_failure_code",
)
